### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by Katatje**

### CODE REVIEW

**Comment by linustouchtips** [comment]
hey! be nice >:(

**Comment by yagel15637** [comment]
You're being toxic for no reason. FYI, you were using the setting system wrong. The entire point with Optionals is null safety, your code looked bad because it was not utilizing it the way it should've. The ModuleManager being a utility class isn't a problem, or monkey code, it's a choice, and IMO a good one at that as it makes the code cleaner (f12aa0c).

**Comment by olliem5** [comment]
cool but why toxic :c

**Comment by Katatje** [comment]
https://github.com/olliem5/clientbase/blob/main/src/main/java/me/olliem5/clientbase/ClientBase.java#L43

**Comment by 69hr** [comment]
told you all it was a paste 🥱

**Comment by 69hr** [comment]
yoink best dev -69hr

**Comment by olliem5** [comment]
> I removed littledraily's pasted event system, I fixed the annotation for you because you were using the wrong one. I removed the unused dependency's that were in kamis buildscript. I fixed your interesting [color util](https://github.com/olliem5/clientbase/blob/810f65fe64476f375fe3273c3bf036a3298f1803/src/main/java/me/olliem5/clientbase/util/ColourUtil.java#L15). You were using an unused `setup` method while there is a thing called a contructor. I reformatted some stuff because it wasn't in order. I made categories have an actual name. I made modules toggleable and I reformatted some stuff. You are making the module manager static but you are creating a [new instance of it](https://github.com/olliem5/clientbase/blob/main/src/main/java/me/olliem5/clientbase/ClientBase.java#L43). I wasn't toxic because of bad code. I was kind of angry that littledraily made a bloated version of my [event manager](https://cdn.discordapp.com/attachments/782147278587953183/785482361465864192/unknown.png) without giving credit at all and I found about it through this.

Sorry I didn't look into this more, I was on mobile this morning. I haven't put much time into this project, due to other things taking priority. I would suggest taking this matter up on [LittleDraily's repo](https://github.com/LittleDraily/event-system) with a more descriptive issue than '🧐' rather than here. Sorry for misinterpreting your anger, and thanks for the contributions!

**Comment by linustouchtips** [comment]
forge event system 💪

**Comment by Katatje** [comment]
I know I probably sounded angry in some of the commit messages O_O

**Comment by LittleDraily** [comment]
Ah kk, i see it too, i didn't particularly skid. I didn't even see your even manager till now!i will try to change it

**Comment by yagel15637** [comment]
> I know I probably sounded angry in some of the commit messages O_O

haha yeah, dw tho

**Comment by yagel15637** [comment]
> forge event system 💪

my event system 💪 💪 💪

**Pull request merged**
